// Duplicated on purpose in frontend/src/lib/constants.js. Change both together.

const freeze = Object.freeze;

export const ROLES = freeze({
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  ORG_MEMBER: 'ORG_MEMBER',
});

export const ORG_STATUS = freeze({
  PENDING: 'PENDING',
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
});

export const USER_STATUS = freeze({
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED',
});

export const SUBSCRIPTION_STATUS = freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

export const TRANSACTION_STATUS = freeze({
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  ROLLED_BACK: 'ROLLED_BACK',
});

export const NOTIFICATION_KIND = freeze({
  MEMBER_INVITED: 'MEMBER_INVITED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  SUBSCRIPTION_UPGRADED: 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_DOWNGRADED: 'SUBSCRIPTION_DOWNGRADED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
});

export const TOKEN_PURPOSE = freeze({
  INVITE: 'INVITE',
  PASSWORD_RESET: 'PASSWORD_RESET',
});

// Every value the API can put in error.code. See the API surface spec.
export const ERROR_CODE = freeze({
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_REUSED: 'REFRESH_REUSED',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  ORG_NOT_ACTIVE: 'ORG_NOT_ACTIVE',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  NAME_IN_USE: 'NAME_IN_USE',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  LAST_ADMIN: 'LAST_ADMIN',
  SEAT_LIMIT_REACHED: 'SEAT_LIMIT_REACHED',
  SUBSCRIPTION_CONFLICT: 'SUBSCRIPTION_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
});

// The three organization status gate tiers. See the API surface spec.
export const ORG_GATE = freeze({
  ANY: freeze([
    ORG_STATUS.PENDING, ORG_STATUS.TRIAL, ORG_STATUS.ACTIVE,
    ORG_STATUS.CANCELLED, ORG_STATUS.SUSPENDED,
  ]),
  BILLABLE: freeze([
    ORG_STATUS.PENDING, ORG_STATUS.TRIAL, ORG_STATUS.ACTIVE, ORG_STATUS.CANCELLED,
  ]),
  OPERATING: freeze([
    ORG_STATUS.TRIAL, ORG_STATUS.ACTIVE, ORG_STATUS.CANCELLED,
  ]),
});

export const PG_UNIQUE_VIOLATION = '23505';
